repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: mypy-kb
        files: ^tools/scripts/
        entry: mypy tools/scripts/
        pass_filenames: false
        additional_dependencies:
          - types-python-slugify==6.1.0
          - types-PyYAML==6.0.9
          - types-requests==2.28.0
          - types-urllib3==1.26.15